---
- name: rename computer
  win_hostname:
    name: "W11HGAMING"
  notify: reboot windows

- name: change power plan to high performance
  community.windows.win_power_plan:
    name: high performance
  notify: reboot windows

- name: windows updates
  win_updates:
    category_names: ["*"]
    reboot: true
  register: windows_updates
  until: not windows_updates.changed
  delay: '{{ global_delay }}'

- name: nvidia display driver
  win_chocolatey:
    name: nvidia-display-driver
    state: latest
    params:
      '/NoAudio /NoUSBC'
  register: nvidia_display_driver
  until: nvidia_display_driver.rc == 0
  delay: '{{ global_delay }}'
  notify: reboot windows

- name: install wsl2
  win_chocolatey:
    name: wsl2
    state: latest
  notify: reboot windows

- name: get installed wsl distros
  win_command: wsl -l -q
  register: wsl_distros
  changed_when: false

- name: install ubuntu if missing
  win_command: wsl --install -d {{ wsl_ubuntu_distro }}
  when: "'{{ wsl_ubuntu_distro }}' not in (wsl_distros.stdout | regex_replace('\\x00', ''))"
  notify: reboot windows

- name: reboot
  meta: flush_handlers